// src/lib/constants.ts
import { Bank, CurrencyRate, Transaction, Notification, Card, Beneficiary } from '@/types';

export const NIGERIAN_BANKS: Bank[] = [
  { code: '044', name: 'Access Bank', slug: 'access-bank' },
  { code: '023', name: 'Citibank Nigeria', slug: 'citibank' },
  { code: '050', name: 'Ecobank Nigeria', slug: 'ecobank' },
  { code: '070', name: 'Fidelity Bank', slug: 'fidelity-bank' },
  { code: '011', name: 'First Bank of Nigeria', slug: 'first-bank' },
  { code: '214', name: 'First City Monument Bank', slug: 'fcmb' },
  { code: '058', name: 'Guaranty Trust Bank', slug: 'gtbank' },
  { code: '030', name: 'Heritage Bank', slug: 'heritage-bank' },
  { code: '301', name: 'Jaiz Bank', slug: 'jaiz-bank' },
  { code: '082', name: 'Keystone Bank', slug: 'keystone-bank' },
  { code: '526', name: 'Parallex Bank', slug: 'parallex-bank' },
  { code: '076', name: 'Polaris Bank', slug: 'polaris-bank' },
  { code: '039', name: 'Stanbic IBTC Bank', slug: 'stanbic-ibtc' },
  { code: '232', name: 'Sterling Bank', slug: 'sterling-bank' },
  { code: '032', name: 'Union Bank of Nigeria', slug: 'union-bank' },
  { code: '033', name: 'United Bank for Africa', slug: 'uba' },
  { code: '215', name: 'Unity Bank', slug: 'unity-bank' },
  { code: '035', name: 'Wema Bank', slug: 'wema-bank' },
  { code: '057', name: 'Zenith Bank', slug: 'zenith-bank' },
  { code: '999', name: "O'Money", slug: 'omoney' },
];

export const COUNTRIES = [
  { code: 'US', name: 'United States', currency: 'USD', flag: '🇺🇸' },
  { code: 'GB', name: 'United Kingdom', currency: 'GBP', flag: '🇬��' },
  { code: 'DE', name: 'Germany', currency: 'EUR', flag: '🇩🇪' },
  { code: 'FR', name: 'France', currency: 'EUR', flag: '🇫🇷' },
  { code: 'CA', name: 'Canada', currency: 'CAD', flag: '🇨🇦' },
  { code: 'GH', name: 'Ghana', currency: 'GHS', flag: '🇬🇭' },
  { code: 'KE', name: 'Kenya', currency: 'KES', flag: '🇰🇪' },
  { code: 'ZA', name: 'South Africa', currency: 'ZAR', flag: '🇿🇦' },
  { code: 'CN', name: 'China', currency: 'CNY', flag: '🇨🇳' },
  { code: 'AE', name: 'United Arab Emirates', currency: 'AED', flag: '🇦🇪' },
];

export const TRANSFER_PURPOSES = [
  'Personal Transfer',
  'Family Support',
  'Education',
  'Medical',
  'Business Payment',
  'Investment',
  'Travel',
  'Property Purchase',
  'Loan Repayment',
  'Other',
];

export const CURRENCY_RATES: CurrencyRate[] = [
  { from: 'NGN', to: 'USD', rate: 0.00063, change: -0.5 },
  { from: 'NGN', to: 'GBP', rate: 0.00050, change: 0.3 },
  { from: 'NGN', to: 'EUR', rate: 0.00058, change: -0.2 },
  { from: 'NGN', to: 'GHS', rate: 0.0076, change: 1.2 },
  { from: 'NGN', to: 'KES', rate: 0.097, change: 0.1 },
];

export const MOCK_TRANSACTIONS: Transaction[] = [
  {
    id: 'txn_001',
    userId: 'usr_001',
    type: 'debit',
    category: 'transfer',
    amount: 50000,
    currency: 'NGN',
    description: 'Transfer to Adebayo Johnson',
    reference: 'OM-LK8F2N-A3B',
    status: 'completed',
    recipientName: 'Adebayo Johnson',
    recipientBank: 'GTBank',
    recipientAccount: '0123456789',
    fee: 25,
    date: new Date(Date.now() - 3600000).toISOString(),
    balanceAfter: 2450000,
  },
  {
    id: 'txn_002',
    userId: 'usr_001',
    type: 'credit',
    category: 'deposit',
    amount: 500000,
    currency: 'NGN',
    description: 'Salary Payment - TechCorp Ltd',
    reference: 'OM-MN9G3P-B4C',
    status: 'completed',
    recipientName: 'Self',
    recipientBank: "O'Money",
    recipientAccount: '3012345678',
    fee: 0,
    date: new Date(Date.now() - 86400000).toISOString(),
    balanceAfter: 2500000,
  },
  {
    id: 'txn_003',
    userId: 'usr_001',
    type: 'debit',
    category: 'international',
    amount: 200000,
    currency: 'NGN',
    description: 'International Transfer to John Smith (USD 126)',
    reference: 'OM-QR5H7K-C5D',
    status: 'completed',
    recipientName: 'John Smith',
    recipientBank: 'Chase Bank',
    recipientAccount: '****4521',
    recipientCountry: 'US',
    fee: 2500,
    date: new Date(Date.now() - 172800000).toISOString(),
    balanceAfter: 2000000,
  },
  {
    id: 'txn_004',
    userId: 'usr_001',
    type: 'debit',
    category: 'payment',
    amount: 15000,
    currency: 'NGN',
    description: 'DSTV Subscription',
    reference: 'OM-ST6J8L-D6E',
    status: 'completed',
    recipientName: 'Multichoice',
    recipientBank: 'System',
    recipientAccount: 'N/A',
    fee: 100,
    date: new Date(Date.now() - 259200000).toISOString(),
    balanceAfter: 2200000,
  },
  {
    id: 'txn_005',
    userId: 'usr_001',
    type: 'credit',
    category: 'transfer',
    amount: 75000,
    currency: 'NGN',
    description: 'Transfer from Chioma Okafor',
    reference: 'OM-UV7K9M-E7F',
    status: 'completed',
    recipientName: 'Self',
    recipientBank: "O'Money",
    recipientAccount: '3012345678',
    fee: 0,
    date: new Date(Date.now() - 345600000).toISOString(),
    balanceAfter: 2215000,
  },
  {
    id: 'txn_006',
    userId: 'usr_001',
    type: 'debit',
    category: 'transfer',
    amount: 30000,
    currency: 'NGN',
    description: 'Transfer to Emeka Nwosu',
    reference: 'OM-WX8L0N-F8G',
    status: 'pending',
    recipientName: 'Emeka Nwosu',
    recipientBank: 'Zenith Bank',
    recipientAccount: '2098765432',
    fee: 25,
    date: new Date(Date.now() - 1800000).toISOString(),
    balanceAfter: 2420000,
  },
  {
    id: 'txn_007',
    userId: 'usr_001',
    type: 'debit',
    category: 'transfer',
    amount: 10000,
    currency: 'NGN',
    description: 'Airtime Purchase - MTN',
    reference: 'OM-YZ9M1O-G9H',
    status: 'completed',
    recipientName: 'MTN Nigeria',
    recipientBank: 'System',
    recipientAccount: '08012345678',
    fee: 0,
    date: new Date(Date.now() - 432000000).toISOString(),
    balanceAfter: 2140000,
  },
  {
    id: 'txn_008',
    userId: 'usr_001',
    type: 'debit',
    category: 'international',
    amount: 150000,
    currency: 'NGN',
    description: 'Transfer to Kwame Asante (GHS 912)',
    reference: 'OM-AB0N2P-H0I',
    status: 'completed',
    recipientName: 'Kwame Asante',
    recipientBank: 'Ecobank Ghana',
    recipientAccount: '****7832',
    recipientCountry: 'GH',
    fee: 1500,
    date: new Date(Date.now() - 518400000).toISOString(),
    balanceAfter: 2150000,
  },
];

export const MOCK_CARDS: Card[] = [
  {
    id: 'card_001',
    userId: 'usr_001',
    cardNumber: '4532 1234 5678 9012',
    cardHolder: 'OLUWASEUN ADEYEMI',
    expiryDate: '12/27',
    type: 'visa',
    variant: 'virtual',
    status: 'active',
    balance: 250000,
    currency: 'NGN',
    dailyLimit: 500000,
  },
  {
    id: 'card_002',
    userId: 'usr_001',
    cardNumber: '5412 7534 9087 3456',
    cardHolder: 'OLUWASEUN ADEYEMI',
    expiryDate: '06/26',
    type: 'mastercard',
    variant: 'physical',
    status: 'active',
    balance: 150000,
    currency: 'USD',
    dailyLimit: 2000,
  },
];

export const MOCK_NOTIFICATIONS: Notification[] = [
  {
    id: 'notif_001',
    title: 'Transfer Successful',
    message: 'Your transfer of ₦50,000 to Adebayo Johnson was successful.',
    type: 'success',
    read: false,
    date: new Date(Date.now() - 3600000).toISOString(),
  },
  {
    id: 'notif_002',
    title: 'Money Received',
    message: 'You received ₦500,000 from TechCorp Ltd.',
    type: 'info',
    read: false,
    date: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: 'notif_003',
    title: 'Security Alert',
    message: 'A new device was used to access your account. If this wasn\'t you, please contact support.',
    type: 'warning',
    read: true,
    date: new Date(Date.now() - 172800000).toISOString(),
  },
];

export const MOCK_BENEFICIARIES: Beneficiary[] = [
  {
    id: 'ben_001',
    accountNumber: '0123456789',
    accountName: 'Adebayo Johnson',
    bankName: 'GTBank',
    bankCode: '058',
    country: 'NG',
    isInternational: false,
  },
  {
    id: 'ben_002',
    accountNumber: '2098765432',
    accountName: 'Emeka Nwosu',
    bankName: 'Zenith Bank',
    bankCode: '057',
    country: 'NG',
    isInternational: false,
  },
  {
    id: 'ben_003',
    accountNumber: '****4521',
    accountName: 'John Smith',
    bankName: 'Chase Bank',
    bankCode: 'CHASUS33',
    country: 'US',
    isInternational: true,
  },
];

export const SPENDING_DATA = [
  { month: 'Aug', income: 450000, expenses: 320000 },
  { month: 'Sep', income: 500000, expenses: 280000 },
  { month: 'Oct', income: 480000, expenses: 350000 },
  { month: 'Nov', income: 520000, expenses: 300000 },
  { month: 'Dec', income: 600000, expenses: 450000 },
  { month: 'Jan', income: 500000, expenses: 295000 },
];